### ISSUE TITLE
Ping taking forever to fail

### ISSUE THREAD

**Issue by Sir-Will** [xrjr/mcutils#1]
Hey,

when the ping handshake is being executed on an old protocol server like 1.6.4 it takes like 15+ seconds until it returns the error.
When using the command, it returns an error instantly, for some reason.

After some troubleshooting, I could only find out that it hangs with the first call of `in.ReadUVarInt()` but I couldn't figure out what's causing it.
https://github.com/xrjr/mcutils/blob/master/pkg/ping/client.go#L37

**Comment by xrjr** [comment]
Hey,

Thank you for your feedback.

According to [https://wiki.vg/Server_List_Ping](https://wiki.vg/Server_List_Ping) :

> The SLP process changed in 1.7 in a non-backwards compatible way

This library may be supporting older versions in the future, but it is not the case as of now.

At the moment, I'm going to update the README to explicitly tell which versions are supported. I will also try to find out why there is a difference of behavior.

**Comment by Sir-Will** [comment]
Thank you for your reply.

I'm aware that older versions are not supported because of the different protocol.
The issue I'm facing is that it takes longer than it supposed to, to throw an error about it. I'm handling the error in my script, but the error is only returned after 15+ seconds.

When I run the CLI command `mcutils ping legacy.mym.li 25565` it doesn't hang though. Only when I use the simple or full ping methods in my own script: https://github.com/xrjr/mcutils#ping

I used this (https://github.com/whatupdave/mcping) old library before, which instantly returns the ErrPacketType error:
https://github.com/whatupdave/mcping/blob/45b6a3b38c1415180d991c6a00ccc95abfa5df84/ping.go#L98

**Comment by Sir-Will** [comment]
During troubleshooting, I added some logging to your library:
```go
func parseHandshakeResponse(in networking.Input) (*handshakeResponse, error) {
	var hsRes handshakeResponse
	print("in ", in)

	length, err := in.ReadUVarInt()
	print("length ", length)
	if err != nil {
		return nil, err
	}
.....
```
Which printed:
```
[27.12.2021 18:10:36.709] in %!(EXTRA networking.Input={0xc0000100e8})
[27.12.2021 18:11:06.819] length %!(EXTRA uint64=127)
```
As you can see from the timestamps, the `in.ReadUVarInt()` took forever.

**Comment by xrjr** [comment]
I cannot reproduce your issue, using the following snippet :

```go
// simple
infos, lat, err := ping.Ping("legacy.mym.li", 25565)
fmt.Println(infos, lat, err)

// full
client := ping.NewClient("legacy.mym.li", 25565)
err = client.Connect()
fmt.Println(err)

infosH, err := client.Handshake()
fmt.Println(infosH, err)

lat, err = client.Ping()
fmt.Println(lat, err)

err = client.Disconnect()
fmt.Println(err)
```

Both versions returned an error rapidly. Can you tell me your OS ?

**Comment by Sir-Will** [comment]
I found out why it was working with the command. I was using `legacy.mym.li` with the command while I used `legacy.mineyourmind.net` with the script (they both point to the same IP address).
Looking at the domain DNS settings, the main difference I see is that `legacy.mineyourmind.net` has an old, unused SRV record:
  `_minecraft._tcp.resurrection    25569    resurrection.mineyourmind.net`

I assume that's triggering the issue, but should that be taking that long?
> Can you tell me your OS ?

MacOS 11

**Comment by xrjr** [comment]
Ok I figured it out. The issue isn't about SRV.

Once the connection is opened, Notchian servers (at least <=1.6) send ping response after 30 seconds, no matter what was sent by the client.

The library is trying to read response from the connection, but it blocks until 30 seconds later when an invalid response is sent, and an error is raised.

The solution can be adding user defined read timeout, or support pre 1.7 SLP.

**Comment by Sir-Will** [comment]
Ah, why is the issue not occurring with `legacy.mym.li` though?

**Comment by xrjr** [comment]
`legacy.mym.li` immediately responds :

```
DecoderException : net.md_5.bungee.protocol.BadPacketException: Unknown packet id 99 @ io.netty.handler.codec.ReplayingDecoder:417
```

That occurs when I send post-1.7 handshake request. However, if I don't send anything it responds after 30 seconds.

Those servers aren't using the same software, are they ?

**Comment by Sir-Will** [comment]
Both `legacy.mym.li` and `legacy.mineyourmind.net` point to the same server with the same bungeecord. So both addresses should have or not have the issue.

The only difference are few DNS entries on the domain like the SRV record mentioned above.

**Comment by Slind14** [comment]
I would guess that it is looking up the SRV record although it is for a different sub-domain.

**Comment by xrjr** [comment]
I didn't lookup SRV while doing my tests...

**Comment by Sir-Will** [comment]
If I use the IP instead of domain it's working too. `mcutils ping 116.202.235.9 25565`
If I use the port form the SRV record it hangs: `mcutils ping 116.202.235.9 25569`

**Comment by xrjr** [comment]
For the exact same request, with and without skipping SRV lookup :

`legacy.mym.li` responds immediately with :

```
???cDecoderException : net.md_5.bungee.protocol.BadPacketException: Unknown packet id 46 @ io.netty.handler.codec.ReplayingDecoder:417
```

`legacy.mineyourmind.net` hangs, and after 30 seconds responds with :

```
??cReadTimeoutException : null
```

`116.202.235.9:25569` just times out during dial, which means server is unreachable.

It may be an issue with BungeeCord, as host and port are transmitted in the handshake request packet.

**Comment by xrjr** [comment]
It's definitely a BungeeCord issue :

Pinging `legacy.mym.li`, transmitting `legacy.mineyourmind.net` in the handshake request payload hangs.
Pinging `legacy.mineyourmind.net`, transmitting `legacy.mym.li` in the handshake request payload raises an error immediately.

**Comment by Sir-Will** [comment]
Hm, that's weird.
The mcping library doesn't seem to have the issue. https://github.com/whatupdave/mcping

**Comment by xrjr** [comment]
mcping sends a protocol version of 109 (ie 1.9). mcutils/ping sends a protocol version of -1, by following the [standard page](https://wiki.vg/Server_List_Ping) :

> If the client is pinging to determine what version to use, by convention -1 should be set.

By setting the protocol version to 109, mcutils/ping raises an error immediately.

I'm not going to change this behavior, because standard states to send -1, and post-1.7 ping protocol shouldn't be used on pre-1.7 servers as there always will be undefined behaviors (even if I put a protocol version of 109).

I plan to support legacy ping version in the near future.

**Comment by xrjr** [comment]
I just added legacy ping support. You should be able to use it with your 1.6.4 server.

**Comment by Sir-Will** [comment]
Oh, thank you. I will look into implementing a timeout for this issue.

**Comment by Sir-Will** [comment]
What approach would you recommend when it's unknown what protocol the server is using and to be able to tell the difference between offline and wrong protocol?

**Comment by xrjr** [comment]
Offline usually raises an error immediately because tcp connection can't be established. The error is raised while calling `PingClient.Connect`.

**Comment by Sir-Will** [comment]
Alright, thanks.
I have added two timeouts now. One for the handshake request and one overall.
When the handshake request times out or throws an error, I call the legacy ping.

**Comment by xrjr** [comment]
I've added built-in timeouts support in v1.2.0.
This may be useful for your use-case.

**Comment by Sir-Will** [comment]
Oh, thank you, that makes it easier.
