### ISSUE TITLE
Slow ping performance

### ISSUE THREAD

**Issue by Sir-Will** [xrjr/mcutils#13]
After completing the implementation and replacing [mcping](https://github.com/whatupdave/mcping) I have noticed that a lot of ping requests timeout with a timeout of 3 seconds and a global timeout of 6 seconds.
I'm running workers to handle almost 1k ping requests at the same time.

With mcping this takes less than 2 seconds to process all 1k addresses with a timeout of 1 second for each request.

mcutils finishes after 4-5 seconds, causing it to frequently hit the global timeout while the per-request timeout is lower.
Reducing the DialTimeout and ReadTimeout from 3 seconds to 1 (to have the same timeout as mcping), results in a time less than 3 seconds but with a lot more requests failing with a timeout.

So it seems that mcutils takes a lot longer to process the requests. Is there any way this can be improved?

**Comment by xrjr** [comment]
I've made a few optimizations here and there, avoiding lots of small read call on connection. You can test it on optimizations branch.

**Comment by Sir-Will** [comment]
Unfortunately, I did not really notice any difference with these changes.

I discovered today that reducing the workers from 1k to 500, without changing the timeouts, will give a higher chance of success, with a time of around 6 seconds.

**Comment by xrjr** [comment]
I've looked through `mcping`'s source code, and I noticed a few differences:
- connection reader is wrapped in a `bufio.Reader`, but very few `Read` calls are made on `optimizations` branch version so it shouldn't make a difference.
- it has a dependency to retrieve informations from JSON, but again it shouldn't make a difference.
- it only performs handshake request.

That last one can be the reason of your issue. `mcutils`'s `ping.Ping` functions performs a full SLP sequence, i.e. it performs a handshake request (that retrieve informations) and a ping request (that is used to determine latency). `mcping` doesn't perform that ping request (which is not mandatory), which reduces the number of requests by 2. It can explain your results.

You can avoid performing that additional ping request by using the `ping.PingClient` and calling only `ping.PingClient.Handshake`. It is documented in the `full control way` section of the README.

**Comment by Sir-Will** [comment]
I removed the `pingclient.Ping()` request, but it seems to not make a difference.

**Comment by xrjr** [comment]
I am very surprised that it doesn't make a difference.

Mcutils tries to resolve SRV record so it sends a request to a DNS server at dial time. This is the last reason I can think about right now.

If you don't use it, you can skip that SRV resolving part using the option of the client.

Can you send me a snippet that enables me to reproduce the issue ? (the data and code you use for mcutils and mcping would be perfect so I can test which part of the program takes too long)

**Comment by xrjr** [comment]
I just released `v1.2.1` (merged #14).

So I've made my own tests on 1k requests. I used `v1.2.1` and wrote this function :

```go
func customping(hostname string, port int) (ping.Handshake, error) {
	client := ping.NewClient(hostname, port)
	client.SkipSRVLookup = true

	err := client.Connect()
	if err != nil {
		return ping.Handshake{}, err
	}

	infos, err := client.Handshake()
	if err != nil {
		return ping.Handshake{}, err
	}

	err = client.Disconnect()
	if err != nil {
		return ping.Handshake{}, err
	}

	return infos, nil
}
```

So you can see I only perform `handshake` request, and I **skip SRV resolving**. I don't change any timeout. Of course I will not be able to ping some servers that are using SRV records.

I measured how much requests failed, and how much time it takes to perform all 1k requests, for both `mcutils`and `mcping`. The results I got were totally equivalent.

**Comment by Sir-Will** [comment]
Thank you for your input.

I actually tested it beforehand with SRV lookup disabled, but after some debugging and pprof profiling, I realized that I forgot to disable it for the legacy ping.

So with `SkipSRVLookup` set to true and a timeout of 1 second, I was able to achieve the same time of less than 2 seconds.

**Comment by Sir-Will** [comment]
Hey @xrjr, is it normal that `mcutils ping-legacy crash.mineyourmind.net 25565` (latency 240ms) is slower than `mcutils ping-legacy-1.6.4 crash.mineyourmind.net 25565` (latency 40ms)?

**Comment by xrjr** [comment]
Hey @Sir-Will, it seems that your server is running behind a proxy. Pre 1.6 ping requests doesn't send informations about the hostname and port you're trying to connect to. You can see that the two requests show different MOTD for example. I don't know your architecture but I suspect that one request is served by the proxy while the other is served by the actual server instance.
