### ISSUE TITLE
Lack of types for ping response

### ISSUE THREAD

**Issue by ClayMav** [xrjr/mcutils#3]
mcutils' value proposition is consolidated support for Minecraft functions, but it currently does not have types for the ping response.

**Comment by xrjr** [comment]
Ping response is a version/implementation specific JSON object. Ping's response is a map[string]interface{} which is Golang's idiomatic way of handling unknown JSON objects.

You can enumerate it, or test if the map contains a key and type assert the value if it is the case.

**Comment by xrjr** [comment]
I decided to add a new type, `Infos`, that contains main SLP informations. You can easily extract an `Infos` from a `ping.JSON` (alias for `map[string]interface{}`) using `ping.JSON.Infos` method.

Example :

```go
response, latency, err := ping.Ping("localhost", 25565)
infos := response.Infos()
fmt.Println(infos.Players.Online)
```
