### ISSUE TITLE
Possible forever query

### ISSUE THREAD

**Issue by CDFN** [xrjr/mcutils#9]
Hey, I have a small problem. I'm trying to query many servers in goroutines using producer-consumer pattern but it seems that the package has deadlock somewhere. Is it possible to maybe implement some kind of timeout? My consumers are getting clogged after some time and after some investigation it seems that query is responsible for that lock. I'm not sure what's going on internally in lib, haven't been digging into it. It would be great if anyone could look into it, if you need more details please dont hestitate to ask.

**Comment by xrjr** [comment]
Hey,

Indeed I need a few informations :
- version of the lib
- protocol (query ?)
- does it happens always on same servers (if yes, can tell me which so I can reproduce the issue)

If you're using Query protocol, version >= 1.0.0, and it doesn't happens always on same servers, it may be an UDP issue. Query is using UDP protocol under the hood, and UDP does **not** guarantee that packets sent will be received.

**Comment by CDFN** [comment]
Version: `github.com/xrjr/mcutils@v1.1.1`
Protocol: query basic
It hangs on some servers, one of them is e.g. `us.mineplex.com` with port `25565`. 
I use following code:
`basic, err := query.QueryBasic(s.Address, s.Port)`
and it just hangs forever.

**Comment by CDFN** [comment]
After attaching debugger I managed to find it hangs on handshake

**Comment by xrjr** [comment]
Ok I may have found out. This issue also happens to `mc.hypixel.net`. Those huge servers uses proxies (such as BungeeCord) that seems to be accepting UDP connections, but doesn't respond to Query (maybe it is not allowed, maybe it's not implemented).

Other libraries seems to be handling it by adding timeouts/read deadlines. I'll add this kind of feature soon.
